apiVersion: v1
kind: Service
metadata:
  name: channels
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app: channels

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
  - port: 5432

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
    nodePort: 30443
  type: NodePort
  selector:
    app: frontend

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    app: web
